# Generated by Django 2.2 on 2020-08-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Остаток')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_basket', to='webapp.Product', verbose_name='Товары')),
            ],
        ),
    ]
