# Generated by Django 2.2 on 2020-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_order_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='orders', through='webapp.ProductOrder', to='webapp.Product', verbose_name='Продукты'),
        ),
    ]
